#version: '2.1'
#services:
#  postgresql:
#    image: docker.io/bitnami/postgresql:11
#    volumes:
#      - 'postgresql_data:/bitnami/postgresql'
#    environment:
#      - 'ALLOW_EMPTY_PASSWORD=yes'
version: "3"
services:
  postgresql:
    image: postgres:14.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: playground
    container_name: 'postgresql-container'
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5556:5432
  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6432:6432
    environment:
      - POSTGRESQL_HOST=postgresql
      - PGBOUNCER_AUTH_TYPE=trust
volumes:
  postgresql_data:
    driver: local
